#!/usr/bin/env python3
# ------------------------------------------------------------------------------
#  Author: Erik Buchholz
#  E-mail: e.buchholz@unsw.edu.au
# ------------------------------------------------------------------------------
"""This module contains the different colors for the plots."""

blue = '#377eb8'
orange = '#ff7f00'
green = '#4daf4a'
red = '#e41a1c'
purple = '#984ea3'
brown = '#a65628'
pink = '#f781bf'
gray = '#999999'
yellow = 'gold'
lightblue = '#92c5de'
lightgreen = '#bae4b3'
lightorange = '#fed98e'
darkorange = '#d95f0e'
maroon = "#7f0000"
# Generated by Colorbrewer:
bar_colors = [red, blue, green, purple, orange, yellow,
              brown, pink, gray]
